  { ID1: 1eoLEeidp72jUeAPwfDUKHBJs9OHx7f0PO3cmj3aFBEA,
  ID1V1: 1_iDGD9XEd5Lw_AvmVo3XkAa4rBstaemnHeLKpyTgt8g,
  ID2: 1R9gfgth7XGm1Z5A2IStYVoxpNej1balmDsODyU5-ljU,
  ID2V1: 1JshfkqgC8bLhATHHkN3D5Bto19Sp3BpMBTYuAts5z_c,
  ID3: 17rIcj6djv7NmIC3RV16VGVkv7tTJgUd8UGvk8ruMOmU,
  ID4: 12rDOluh8jReO5Ss-YqrM1eUIpZLF0zHpxyt9n84TkWU,
  Source1: 'https://raw.githubusercontent.com/LukeBlueLOx/SARS-CoV-2_PL_V_2.0/main/DATA/Source1/',
  Source2: 'https://raw.githubusercontent.com/LukeBlueLOx/SARS-CoV-2_PL_V_2.0/main/DATA/Source2/',
  T1: Voivodeships-V2, T2: Districts-V2, T3: Computable-V2, T4: DATA-V2,
  api_daily_data_Source1: 'https://api.dane.gov.pl/resources/33185,aktualne-dane-dla-wojewodztw/file',
  api_daily_data_Source2: 'https://api.dane.gov.pl/resources/33186,aktualne-dane-dla-powiatow/file',
  datetime: '2023-01-30',
  formula1: '=IMPORTRANGE("https://docs.google.com/spreadsheets/d/1_iDGD9XEd5Lw_AvmVo3XkAa4rBstaemnHeLKpyTgt8g"',
  g: "********************", n: 33, sep: ;,
  save_path1: DATA/Source1/voivodeships.zip,
  save_path2: DATA/Source2/districts.zip,
  save_path_extract1: DATA/Source1/,
  save_path_extract2: DATA/Source2/,
  url_source1: 'https://api.dane.gov.pl/resources/33193,archiwalne-dane-dla-wojewodztw/file',
  url_source2: 'https://api.dane.gov.pl/resources/33194,archiwalne-dane-dla-powiatow/file'}
