{CORE: /home/blox_land/SARS-CoV-2_PL_V_2.0/CORE/, ID1: 1eoLEeidp72jUeAPwfDUKHBJs9OHx7f0PO3cmj3aFBEA,
  ID1V1: 1_iDGD9XEd5Lw_AvmVo3XkAa4rBstaemnHeLKpyTgt8g, ID2: 1R9gfgth7XGm1Z5A2IStYVoxpNej1balmDsODyU5-ljU,
  ID2V1: 1JshfkqgC8bLhATHHkN3D5Bto19Sp3BpMBTYuAts5z_c, ID3: 17rIcj6djv7NmIC3RV16VGVkv7tTJgUd8UGvk8ruMOmU,
  ID4: 12rDOluh8jReO5Ss-YqrM1eUIpZLF0zHpxyt9n84TkWU, MAIN: /home/blox_land/SARS-CoV-2_PL_V_2.0/,
  Source1: 'https://raw.githubusercontent.com/LukeBlueLOx/SARS-CoV-2_PL_V_2.0/main/DATA/Source1/',
  Source2: 'https://raw.githubusercontent.com/LukeBlueLOx/SARS-CoV-2_PL_V_2.0/main/DATA/Source2/',
  T1: Voivodeships-V2, T2: Districts-V2, T3: Computable-V2, T4: DATA-V2, api_daily_data_Source1: 'https://api.dane.gov.pl/resources/33185,aktualne-dane-dla-wojewodztw/file',
  api_daily_data_Source2: 'https://api.dane.gov.pl/resources/33186,aktualne-dane-dla-powiatow/file',
  datawrapper_token: '********************', datetime: 2023-02-15, formula1: '=IMPORTRANGE("https://docs.google
    .com/spreadsheets/d/1eoLEeidp72jUeAPwfDUKHBJs9OHx7f0PO3cmj3aFBEA"', formula2: '=IMPORTRANGE("https://docs.google.com/spreadsheets/d/1R9gfgth7XGm1Z5A2IStYVoxpNej1balmDsODyU5-ljU","COMPUTABLE!A1:I382")',
  formula3: '=IMPORTRANGE("https://docs.google.com/spreadsheets/d/17rIcj6djv7NmIC3RV16VGVkv7tTJgUd8UGvk8ruMOmU","IOTR!A1:M29")',
  formula4: '=IMPORTRANGE("https://docs.google.com/spreadsheets/d/12rDOluh8jReO5Ss-YqrM1eUIpZLF0zHpxyt9n84TkWU"',
  g: '********************', heroku_CORE_path: /app/CORE/, heroku_MAIN_path: /app/,
  local_CORE_path: /home/blox_land/SARS-CoV-2_PL_V_2.0/CORE/, local_MAIN_path: /home/blox_land/SARS-CoV-2_PL_V_2.0/,
  n: 1, save_path1: DATA/Source1/voivodeships.zip, save_path2: DATA/Source2/districts.zip,
  save_path_extract1: DATA/Source1/, save_path_extract2: DATA/Source2/, save_path_extract3: DATA/SUM/,
  save_path_extract4: DATA/IOTR/, save_path_extract5: DATA/7DAVRDLR14D/, save_path_extract6: Plotly_Dash/,
  sep: ;, url_source1: 'https://api.dane.gov.pl/resources/33193,archiwalne-dane-dla-wojewodztw/file',
  url_source2: 'https://api.dane.gov.pl/resources/33194,archiwalne-dane-dla-powiatow/file',
  url_source3: 'https://docs.google.com/spreadsheets/d/e/2PACX-1vSZxCw5Pioxm3iAbM0wdglJgCeUAzTd4jOCvv2-fz7dbyDd6hmn4KF6yHr5Gx0uX0JX96KlRcjSg34l/pub?gid=0&single=true&output=csv',
  url_source4: 'https://raw.githubusercontent.com/LukeBlueLOx/SARS-CoV-2_PL_V_2.0/main/'}
